version: 2

jobs:
  build-job:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - checkout

      - restore_cache:
          key: project-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --stacktrace

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}
          paths:
            - ~/android

      - run:
          name: Run whiteboard model test
          command: ./gradlew lib-whiteboard-model:testDebugUnitTest -PtestProguard=true --stacktrace
      - run:
          name: Run whiteboard kit domain test
          command: ./gradlew lib-whiteboard-kit-domain:testDebugUnitTest -PtestProguard=true --stacktrace
      - run:
          name: Run whiteboard editor domain test
          command: ./gradlew lib-whiteboard-editor-domain:testDebugUnitTest -PtestProguard=true --stacktrace
#      - run:
#          name: Run whiteboard app test
#          command: ./gradlew app-whiteboard:testDebugUnitTest -PtestProguard=true --stacktrace

      - store_artifacts:
          path: lib-whiteboard-model/build/outputs/
          destination: outputs/
      - store_artifacts:
          path: lib-whiteboard-kit-domain/build/outputs/
          destination: outputs/
      - store_artifacts:
          path: lib-whiteboard-editor-domain/build/outputs/
          destination: outputs/

      - save_cache:
          key: project-{{ checksum "build.gradle" }}-{{ checksum "dependencies.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle/4.6"
            - "~/.gradle/wrapper/dists/gradle-4.6-all"
            - "~/.gradle/caches/modules-2"
            - "~/.gradle/buildOutputCleanup"
            - "~/.m2"

  deploy-job:
    working_directory: ~/project

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xms256m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'

    steps:
      - checkout

#      - run:
#          name: Download dependencies
#          command: ./gradlew androidDependencies --stacktrace
#
#      - run:
#          name: Run unit test
#          command: ./gradlew testReleaseUnitTest --stacktrace
#
#      - run:
#          name: Build artifact
#          command: ./gradlew build --stacktrace
#
#      - run:
#          name: Publish to Github
#          command: ./gradlew githubRelease
#
#      - run:
#          name: Publish to JCenter
#          command: ./gradlew lib-whiteboard-model::bintrayUpload --stacktrace

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters:
            branches:
              ignore: master
      - deploy-job:
          filters:
            branches:
              only: master
